import static org.hamcrest.Matchers.*;
import static org.junit.Assert.*;
import java.util.*;
import static org.hamcrest.*;
public class RepositoryTest{
  @Test
  public void checkMethods(){
    Band motorhead = new Band(0,"Motorhead","Rock And Roll",3);
    Band metallica = new Band(1,"Metallica","Metal",4);
    Band volbeat = new Band(2,"Volbeat","Groove Metal",5);
    LinkedList<Band> l = new LinkedList<Band>();
    l.add(motorhead);
    l.add(metallica);
    l.add(volbeat);
    BandRepository repo = new BandRepository();

    assertThat(repo.getInfo(), is("baza danych zespołów"));
    assertThat(repo.getAll(),is(l));
    String t = "CREATE TABLE bands("
				+ "_Id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
				+ "_Name varchar(20),"
				+ "_Genre varchar(50),"
				+ "_NumberOfMembers int"
				+ ")";
        assertThat(repo.createTableBand(),is(t));
        assertThat(repo.selectFromBand(0),is(motorhead));
        l.remove(metallica);
        repo.deleteFromBand(1);
        assertThat(repo.selectFromBand(0),is(not(metallica)));
        Band pantera = new Band(3,"Pantera","Groove Metal",4);
        repo.insertToBand(pantera);
        assertThat(repo.selectFromBand(3),is(pantera));
        Band def = new Band(2,"Def Leppard","Groove Metal",6);
        repo.updateById(2,def);
        assertThat(repo.selectFromBand(2),is(pantera));
        t = "DROP TABLE bands;";
        assertThat(repo.dropTableBand(),is("DROP TABLE bands;"));
        assertThat(repo.getAll(),is(null));



  }
}
